### ISSUE TITLE
Transport Error - ssh: connect to host 127.0.0.1 port 22: Connection refused

### ISSUE THREAD

**Issue by amarpg** [openschemas/dockerfiles#9]
I am running this image on container and able to connect over web, however I have an issue
After loading in browser, I am getting this error in the web terminal UI  -- ssh: connect to host 127.0.0.1 port 22: Connection refused

My architecture flow is this way:
Browser(machine A) -> Webserver on machineB->webserver on machine C->Container on machine C with the wetty image.

The error sounds like a trusted ssh relationship issue, but what can be done here to fix this issue as I have multiple hops???

**Comment by vsoch** [comment]
Could you please share the exact command you are running? I'm not sure how much I'll be able to help, because this sounds like an ssl issue, and you'd be best off not having such a complicated setup (that I'm not sure how I'd help you debug).

**Comment by amarpg** [comment]
Hi,
I have followed below steps. I will simplify as some of the flows are not so imp1. Ran your image in a docker container on machine C2. When I open the ip;port on my browser in machine A, the request flows through machinB and then reaches the container on C. 3. I am able to see the web terminal on my browser.4. However, when I start entering login credentials it immediately throws ssh connection refused error.
I can see in your docker file the remote ssl parameters with port 22. Do you expect me to do amy additional configuration?
Regards,Amar

Sent from Yahoo Mail on Android 
 
  On Sat, Nov 9, 2019 at 6:40 PM, Vanessasaurus<notifications@github.com> wrote:   
Could you please share the exact command you are running? I'm not sure how much I'll be able to help, because this sounds like an ssl issue, and you'd be best off not having such a complicated setup (that I'm not sure how I'd help you debug).

**Comment by vsoch** [comment]
Please share the exact command you are running...

**Comment by amarpg** [comment]
Node app.js -p  3000

Sent from Yahoo Mail on Android 
 
  On Sun, Nov 10, 2019 at 7:50 AM, Vanessasaurus<notifications@github.com> wrote:   
Please share the exact command you are running...

**Comment by vsoch** [comment]
Sorry I'm not sure how to help you, there are no node commands or app.js scripts provided in this repository. If you have a specific question about an actual command / piece of software provided here, please let me know. Otherwise, I unfortunately have no way to help you debug your unique setup. Closing issue.
